INSERT INTO users (name, email) VALUES
('Andi Nugraha', 'andi.nugraha@example.com'),
('Putri Lestari', 'putri.lestari@example.com'),
('Dimas Rahman', 'dimas.rahman@example.com'),
('Siti Aisyah', 'siti.aisyah@example.com'),
('Reza Pratama', 'reza.pratama@example.com');

INSERT INTO posts (title, content, user_id) VALUES
('Membuat API Login dengan Spring Boot', 'Langkah-langkah membangun login API menggunakan Spring Security.', 1),
('Optimasi Query di MySQL', 'Gunakan indexing dan analisis query plan untuk performa maksimal.', 3),
('Belajar Docker dari Nol', 'Docker sangat berguna untuk membuat environment yang konsisten.', 2),
('Cara Deploy Java App di VPS', 'Langkah-langkah lengkap deploy aplikasi Java ke VPS.', 4),
('Menggunakan Postman untuk Tes API', 'Simulasikan request API dengan mudah menggunakan Postman.', 5),
('Integrasi Spring Boot dengan Redis', 'Redis berguna untuk caching dan session storage.', 1),
('Menggunakan Git Branching dengan Benar', 'Strategi git flow untuk tim pengembangan.', 2),
('Konsep Dasar RESTful API', 'API yang baik mengikuti prinsip REST.', 3),
('Perbandingan JWT vs Session', 'Mana yang lebih cocok untuk aplikasi modern?', 4),
('Logging Efisien di Java', 'Pakai SLF4J dan Logback untuk manajemen log yang rapi.', 5),
('Pengantar Microservices', 'Kenapa microservices penting untuk scalability?', 1),
('Menggunakan Swagger untuk Dokumentasi API', 'Swagger UI membantu tim frontend memahami API.', 2),
('Mengelola Environment Config', 'Gunakan YAML atau dotenv untuk pisahkan konfigurasi.', 3),
('CI/CD dengan GitHub Actions', 'Otomatisasi build dan deploy aplikasi.', 4),
('Testing Service Layer', 'Unit test di service penting untuk menjaga kualitas code.', 5),
('Belajar Konsep Domain Driven Design', 'DDD membantu struktur aplikasi lebih baik.', 1),
('Spring Boot dan RabbitMQ', 'Kirim dan terima pesan antar service.', 2),
('Cara Setting HTTPS di Spring Boot', 'Tambahkan SSL cert untuk keamanan.', 3),
('Konsep MVC di Spring', 'Model-View-Controller membuat kode lebih terorganisir.', 4),
('Throttle API Request', 'Hindari overload dengan rate limiter.', 5),
('Handle Exception Global', 'Gunakan @ControllerAdvice dan ResponseEntity.', 1),
('Integrasi Firebase Cloud Messaging', 'Push notification ke client.', 2),
('Pakai JPA vs Native Query', 'Mana yang lebih fleksibel?', 3),
('Reactive Programming di Spring', 'WebFlux untuk aplikasi non-blocking.', 4),
('Monitoring App dengan Prometheus', 'Ambil metrics dan pantau performa.', 5),
('Cara Setup PostgreSQL di VPS', 'Install dan konfigurasi PostgreSQL.', 1),
('Upload File ke Cloud Storage', 'Integrasi ke AWS S3.', 2),
('Menggunakan MapStruct', 'Mapping object jadi lebih cepat dan bersih.', 3),
('Mengamankan API dengan API Key', 'Cara sederhana untuk kontrol akses.', 4),
('Langkah Migrasi ke Spring Boot 3', 'Apa yang berubah dan bagaimana caranya?', 5);